#!/bin/bash
cookie_BDUSS=""
cookie_BAIDUID=""
cookie_BIDUPSID=""
useragent="Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"

filename="/tmp/UpToBaidu.png"
xclip -t image/png -sel clipboard -o > "$filename"
mimetype="$(file --mime-type "$filename" | sed s#$filename\:\ ## )"
if [[ "$mimetype" != "image/png" ]];then
    notify-send -a "上传失败" "剪贴板中的不是图片"
    rm "$filename"
    exit
fi
success=False
count=1
while [ "$success" = "False" ];do
    curl_out="$(curl -A "$useragent" -s --cookie "BDUSS=${cookie_BDUSS};BAIDUID=${cookie_BAIDUID};BIDUPSID=${cookie_BIDUPSID};userFrom=www.baidu.com;ORIGIN=2" -H "Referer:www.baidu.com" "https://sp0.baidu.com/6_R1fD_bAAd3otqbppnN2DJv/Pic/upload?pid=super&app=skin&logid=2915142959" -F "file=@$filename")"
    test="$(echo "$curl_out" | grep html)"
    test2="$(echo "$curl_out" | grep annoymous)"
    if [[ "$test2" != "" ]];then
        success=True
        notify-send -a "上传失败" "百度账号未登录" "$curl_out"
        rm "$filename"
        exit
    fi
    if [[ "$test" == "" ]];then
        url=$(printf "$curl_out" | jq -r ".data.pic_water" | sed "s/http/https/")
        printf "$url" | xclip -sel clipboard -i
        success=True
        rm "$filename"
        notify-send -a "剪贴板中的截图上传完成" "链接已复制到剪贴板" "共请求 $count 次。"
    else
        count=$(($count+1))
    fi
done
