#!/bin/bash
mkdir -p "/tmp/icalingua.d"
asar e "/usr/lib/icalingua/icalingua.asar" "/tmp/icalingua.d"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Black--fonts.eot"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Black--fonts.ttf"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Black--fonts.woff"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Black--fonts.woff2"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-BlackItalic--fonts.eot"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-BlackItalic--fonts.ttf"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-BlackItalic--fonts.woff"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-BlackItalic--fonts.woff2"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Bold--fonts.eot"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Bold--fonts.ttf"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Bold--fonts.woff"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Bold--fonts.woff2"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-BoldItalic--fonts.eot"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-BoldItalic--fonts.ttf"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-BoldItalic--fonts.woff"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-BoldItalic--fonts.woff2"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Book--fonts.eot"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Book--fonts.ttf"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Book--fonts.woff"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Book--fonts.woff2"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-BookItalic--fonts.eot"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-BookItalic--fonts.ttf"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-BookItalic--fonts.woff"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-BookItalic--fonts.woff2"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Light--fonts.eot"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Light--fonts.ttf"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Light--fonts.woff"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Light--fonts.woff2"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-LightItalic--fonts.eot"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-LightItalic--fonts.ttf"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-LightItalic--fonts.woff"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-LightItalic--fonts.woff2"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Medium--fonts.eot"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Medium--fonts.ttf"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Medium--fonts.woff"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-Medium--fonts.woff2"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-MediumItalic--fonts.eot"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-MediumItalic--fonts.ttf"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-MediumItalic--fonts.woff"
rm "/tmp/icalingua.d/dist/electron/fonts/CircularSpotifyTxT-MediumItalic--fonts.woff2"
rm "/tmp/icalingua.d/dist/electron/fonts/msyh--assets.ttf"
ls "/tmp/icalingua.d/dist/electron/fonts"
sed -i "s/font, 'CircularSpotifyTxT Book Web', msyh, twemoji, 'PingFang SC', /'HarmonyOS Sans SC','Noto Sans CJK SC',/" "/tmp/icalingua.d/dist/electron/renderer.js"
sed -i "s/'CircularSpotifyTxT Light Web'/'HarmonyOS Sans SC','Noto Sans CJK SC'/" "/tmp/icalingua.d/dist/electron/renderer.js"
sed -i "s/'msyh'/'HarmonyOS Sans SC','Noto Sans CJK SC'/" "/tmp/icalingua.d/dist/electron/renderer.js"

mv "/usr/lib/icalingua/icalingua.asar" "/usr/lib/icalingua/icalingua.asar.bak"
asar p "/tmp/icalingua.d" "/usr/lib/icalingua/icalingua.asar"
rm -rf "/tmp/icalingua.d"

######此处 LXGW Bold WenKai 请换成自己所需的字体
